# Generated by Django 4.2.4 on 2023-08-15 08:53

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgound_color_1', models.CharField(default='02557a', max_length=6)),
                ('backgound_color_2', models.CharField(default='c7e0f4', max_length=6)),
                ('text_color_1', models.CharField(default='1b1b1b', max_length=6)),
                ('text_color_2', models.CharField(default='1b1b1b', max_length=6)),
                ('text_color_3', models.CharField(default='ff9001', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='theme',
            field=models.ForeignKey(default=employee.models.get_theme, on_delete=django.db.models.deletion.SET_DEFAULT, to='employee.theme'),
        ),
    ]
